num1 = eval(input("Enter the first number:"))
num2 = eval(input("Enter the second number:"))

print("The sum of", num1, "and", num2, "is",num1 + num2 )
print("The difference of", num1, "and" , num2 ,"is",num1 - num2)
print("The product of" , num1 , "and" , num2 , "is" , num1 * num2)
print("The quotient of" , num1 , "and" , num2 , "is" , num1 / num2)
print("The exponent of" , num1 , "and" , num2 , "is" , num1 ** num2)
print("The remainder of" , num1 , "and" , num2 , "is" , num1 % num2)
print("The floor division of" , num1 , "and" , num2 , "is" , num1 // num2) 